export const ETHERS = "ethers";
export const ETHERS_SET_ACCOUNT = "ETHERS_SET_ACCOUNT";
export const ETHERS_SET_METAMASK_INSTALL_STATUS =
  "ETHERS_SET_METAMASK_INSTALL_STATUS";
export const ETHERS_CONNECTED_ACCOUNT = "ETHERS_CONNECTED_ACCOUNT";
export const ETHERS_IS_ACCOUNT_CONNECTED = "ETHERS_IS_ACCOUNT_CONNECTED";
export const ETHERS_CONNECTED_ACCOUNT_ELLIPSIS =
  "ETHERS_CONNECTED_ACCOUNT_ELLIPSIS";
